services:
  database:
    image: postgres
    container_name: fms-postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fms_db
    ports:
      - "5432:5432"
    volumes:
      # 컨테이너 최초 생성 시 알파벳 순으로 자동 실행 (schema.sql → seed.sql)
      - ./db:/docker-entrypoint-initdb.d


